version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      PGPASSWORD: secret
      POSTGRES_DB: suzume
      POSTGRES_USER: hachi
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
